name: Release STLs

on:
  push:
    tags:
      - 'V*' # This rule triggers the action whenever a tag starting with 'V' is pushed

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare and Zip Standard STLs
        run: |
          FOLDER_NAME="openBrushograph_${GITHUB_REF_NAME}"
          mkdir -p "release_standard/${FOLDER_NAME}/XY_mechanism" "release_standard/${FOLDER_NAME}/Z_mechanism" "release_standard/${FOLDER_NAME}/containerHolders"
          cp -r X-Y_freeCAD/STLs/brushograf_V6_Mini_M3_2.7mm_STLs/* "release_standard/${FOLDER_NAME}/XY_mechanism/" || true
          cp -r Z-mechanism_openSCAD/Z-mechanism_STL/standard/* "release_standard/${FOLDER_NAME}/Z_mechanism/" || true
          cp Extras/new_colour_holder/Gandi_*.stl "release_standard/${FOLDER_NAME}/containerHolders/" || true
          cd release_standard
          zip -r ../Standard_STLs.zip *

      - name: Prepare and Zip Mikro STLs
        run: |
          FOLDER_NAME="openBrushograph_${GITHUB_REF_NAME}"
          mkdir -p "release_mikro/${FOLDER_NAME}/XY_mechanism" "release_mikro/${FOLDER_NAME}/Z_mechanism" "release_mikro/${FOLDER_NAME}/containerHolders"
          cp -r X-Y_freeCAD/STLs/brushograf_V6_Micro_M3_2.7mm_STLs/* "release_mikro/${FOLDER_NAME}/XY_mechanism/" || true
          cp -r Z-mechanism_openSCAD/Z-mechanism_STL/mikro/* "release_mikro/${FOLDER_NAME}/Z_mechanism/" || true
          cp Extras/new_colour_holder/mikro_*.stl "release_mikro/${FOLDER_NAME}/containerHolders/" || true
          cd release_mikro
          zip -r ../Mikro_STLs.zip *

      - name: Create GitHub Release and Upload Zips
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Standard_STLs.zip
            Mikro_STLs.zip
          generate_release_notes: true
